// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SmartBodyDomain.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SbdJsonPersistence - Verify JSON persistence functionality")]
    public partial class SbdJsonPersistence_VerifyJSONPersistenceFunctionalityFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "SbdJsonPersistence.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SbdJsonPersistence - Verify JSON persistence functionality", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("JSON can be written and read again")]
        public virtual void JSONCanBeWrittenAndReadAgain()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("JSON can be written and read again", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
        testRunner.Given("The DiaryWeight JSON persistence is create", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Day",
                            "Weight"});
                table28.AddRow(new string[] {
                            "25.08.2022",
                            "83.00"});
                table28.AddRow(new string[] {
                            "26.08.2022",
                            "82.00"});
                table28.AddRow(new string[] {
                            "27.08.2022",
                            "85.00"});
#line 5
        testRunner.When("These DiaryWeight records shall be used", ((string)(null)), table28, "When ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Day",
                            "Progress"});
                table29.AddRow(new string[] {
                            "25.08.2022",
                            "Normal"});
                table29.AddRow(new string[] {
                            "26.08.2022",
                            "Progress"});
                table29.AddRow(new string[] {
                            "27.08.2022",
                            "Deload"});
#line 10
        testRunner.And("These GymSession records shall be used", ((string)(null)), table29, "And ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "value"});
                table30.AddRow(new string[] {
                            "Start",
                            "01.01.2022"});
                table30.AddRow(new string[] {
                            "End",
                            "31.03.2022"});
#line 15
        testRunner.And("This challenge record is to be used on \'01.01.2022\'", ((string)(null)), table30, "And ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Area",
                            "Length"});
                table31.AddRow(new string[] {
                            "LeftArm",
                            "33.00"});
                table31.AddRow(new string[] {
                            "RightArm",
                            "33.00"});
                table31.AddRow(new string[] {
                            "LeftLeg",
                            "33.00"});
                table31.AddRow(new string[] {
                            "RightLeg",
                            "33.00"});
                table31.AddRow(new string[] {
                            "Shoulder",
                            "33.00"});
                table31.AddRow(new string[] {
                            "Chest",
                            "33.00"});
                table31.AddRow(new string[] {
                            "Belly",
                            "33.00"});
                table31.AddRow(new string[] {
                            "BellyPlus5",
                            "33.00"});
                table31.AddRow(new string[] {
                            "BellyMinus5",
                            "33.00"});
                table31.AddRow(new string[] {
                            "Hip",
                            "33.00"});
#line 19
        testRunner.And("This body data is to be used on \'01.01.2021\'", ((string)(null)), table31, "And ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Day",
                            "Neat",
                            "Sleep",
                            "Macros",
                            "Kcal",
                            "Protein"});
                table32.AddRow(new string[] {
                            "01.01.2022",
                            "Reached",
                            "Unknown",
                            "Missed",
                            "Reached",
                            "Unknown"});
                table32.AddRow(new string[] {
                            "01.02.2022",
                            "Reached",
                            "Unknown",
                            "Missed",
                            "Reached",
                            "Unknown"});
#line 32
        testRunner.And("These daily goals shall be used", ((string)(null)), table32, "And ");
#line hidden
#line 37
        testRunner.And("The data is written to JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
        testRunner.And("The data is read from JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
        testRunner.Then("The previous existing weight records shall be read", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
        testRunner.Then("The previous existing gym session records shall be read", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
        testRunner.Then("The previous existing challenge record shall be read", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
        testRunner.Then("The previous existing body data record shall be read", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
        testRunner.Then("The previous existing daily goals record shall be read", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
